// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ExpandableController from "./expandable_controller"
import HelloController from "./hello_controller"
import PhraseController from "./phrase_controller"

application.register("hello", HelloController)
application.register("phrase", PhraseController)
application.register("expandable", ExpandableController)